name = "SCEDCCorr"
uuid = "d7092747-afd9-464e-8b97-faf53fe1d072"
authors = ["Tim Clements <thclements@g.harvard.edu> and contributors"]
version = "0.1.0"

[deps]
AWSCore = "4f1ea46c-232b-54a6-9b17-cc2d0f3e6598"
AWSS3 = "1c724243-ef5b-51ab-93f4-b0a88ac62a95"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
SeisIO = "b372bb87-02dd-52bb-bcf6-c30dd83fd342"
SeisNoise = "8cc7c3c0-6b5d-11e9-39fe-c9cd0236e08b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
JLD2 = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
